name: Security Audit

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  supply-chain:
    name: 'cargo-audit'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        run: rustup toolchain install stable --no-self-update

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install cargo-audit@0.22.0 --force --locked

      - name: Check for audit warnings
        run: cargo audit -D warnings
        continue-on-error: true

      - name: Check for vulnerabilities
        run: cargo audit
