name: Commits

on:
    push:
    pull_request:

permissions: {}

jobs:
    signatures:
        name: Check PGP Signatures
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Assert Commits are Signed
              run: bash contrib/check-commit-signatures.sh
